@base = {{$processEnv %restjcBaseUrl}}
@event = camp20

### 取得
{{ base }}/events
  ?
  &type=camp

### 登録

POST {{ base }}/event
Content-Type: application/x-www-form-urlencoded

&id={{event}}
&name=てすといべんと
&type=camp
&begin=2019-08-10T17:42:57+09:00
&end=2019-09-17T17:42:59+09:00
